version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "TASK-DEFINITION-ARN"
        LoadBalancerInfo:
          ContainerName: "httpd"
          ContainerPort: 80